### ISSUE TITLE
 Error called ImportError: No module named 'config'

### ISSUE THREAD

**Issue by manoj-shenoy** [coyo8/sec-edgar#13]
from config import DEFAULT_DATA_PATH
ImportError: No module named 'config'

this is the error i get, can u please help

**Comment by jsink13** [comment]
I think the syntax is a little wrong.   You meant to do something like:

from SECEdgar.config import DEFAULT_DATA_PATH
from SECEdgar import config 

But I cannot get the code to actually respect the values I set, it always writes to the default location (next to where the code is)

**Comment by david942j** [comment]
This issue is because of the different behavior of `import` between py2 and py3.
For py3 users, in `SECEdgar/crawler.py`
change `from config import DEFAULT_DATA_PATH`
into `from SECEdgar.config import DEFAULT_DATA_PATH`
as @jsink13 suggested will fix this issue.

BTW, is this work targeting to support py3? Maybe someone can submit a PR to fix this if so.

**Comment by jsnyder8844** [comment]
I'm seeing the same error message:   
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SECEdgar-0.1.3-py3.6.egg/SECEdgar/crawler.py", line 9, in <module>
    from config import DEFAULT_DATA_PATH
ModuleNotFoundError: No module named 'config'

When I go into the crawler.py file, I don't see where I should make the change that @david942j  and @jsink13 suggested. Can you please help?

**Comment by aaronhma** [comment]
Thanks @david942j! It works for me!
